# Generated by Django 5.2.5 on 2025-08-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pandit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pandit_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('Location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pandits',
                'unique_together': {('Pandit_name', 'Location')},
            },
        ),
    ]
